route:
  receiver: pager
  routes:
    - receiver: 'pager'
      mute_time_intervals: 
        - offwork

mute_time_intervals:
  - name: offwork
    time_intervals: 
      - weekdays: ['saturday', 'sunday']
      - times:
        - start_time: 00:00
          end_time: 09:00
        - start_time: 18:00
          end_time: 23:59
      
receivers:
  - name: 'pager'
    webhook_configs:
    - url: http://host.docker.internal:8080 # replace with your PagerTree webhook url