version: '3.2'

services: 

  nodeexporter:
    image: prom/node-exporter:v1.5.0
    command:
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
    expose:
      - 9100
    networks:
      - grafana-performance-lab

  prometheus:
    image: prom/prometheus:v2.42.0
    volumes:
      - ./conf:/etc/prometheus:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    networks:
      - grafana-performance-lab

  grafana:
    image: grafana/grafana:9.3.6
    depends_on:
      - prometheus
    environment:
      GF_FEATURE_TOGGLES_ENABLE: publicDashboards
    volumes:
      - ./grafana-data:/var/lib/grafana
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
    ports:
      - 3000:3000
    networks:
      - grafana-performance-lab
networks:
  grafana-performance-lab:
    driver: bridge